# Generated by Django 5.1.5 on 2025-03-11 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='APIRequestLog',
        ),
    ]
