# Generated by Django 5.1.5 on 2025-02-13 14:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lims_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='borrowrecord',
            unique_together={('user', 'book', 'is_returned')},
        ),
    ]
