# Generated by Django 5.1.5 on 2025-02-14 04:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims_app', '0002_alter_borrowrecord_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='borrowrecord',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='borrowrecord',
            constraint=models.UniqueConstraint(fields=('user', 'book', 'is_returned'), name='unique_borrow_record'),
        ),
    ]
