# Generated by Django 5.1.5 on 2025-02-22 09:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims_app', '0003_alter_book_isbn'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='borrowrecord',
            name='unique_borrow_record',
        ),
        migrations.AlterField(
            model_name='borrowrecord',
            name='return_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='borrowrecord',
            constraint=models.UniqueConstraint(condition=models.Q(('is_returned', False)), fields=('user', 'book'), name='unique_active_borrow'),
        ),
    ]
