# Generated by Django 5.1.5 on 2025-02-25 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims_app', '0004_remove_borrowrecord_unique_borrow_record_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='daily_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
