# Generated by Django 5.1.5 on 2025-03-10 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims_app', '0005_alter_book_daily_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=255, null=True)),
                ('path', models.TextField()),
                ('method', models.CharField(max_length=10)),
                ('status_code', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
