# Generated by Django 5.1.5 on 2025-03-11 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims_app', '0006_apirequestlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='apirequestlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apirequestlog',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
    ]
