# Generated by Django 5.1.5 on 2025-03-12 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims_app', '0007_apirequestlog_ip_address_apirequestlog_user_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
